apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\vladv\Downloads\kompose-windows-amd64.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: auth-db
  name: auth-db
spec:
  ports:
    - name: "5433"
      port: 5433
      targetPort: 5432
  selector:
    io.kompose.service: auth-db
