apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\vladv\Downloads\kompose-windows-amd64.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: auth-db
  name: auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\vladv\Downloads\kompose-windows-amd64.exe convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: auth-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: auth_db
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: POSTGRES_USER
              value: auth_user
          image: postgres
          name: auth-db
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: auth-db-data
      restartPolicy: Always
      volumes:
        - name: auth-db-data
          persistentVolumeClaim:
            claimName: auth-db-data
