apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\vladv\Downloads\kompose-windows-amd64.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: auth-service
  name: auth-service
spec:
  ports:
    - name: "5093"
      port: 5093
      targetPort: 5093
    - name: "50930"
      port: 50930
      targetPort: 50930
  selector:
    io.kompose.service: auth-service
