apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\vladv\Downloads\kompose-windows-amd64.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: auth-service
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\vladv\Downloads\kompose-windows-amd64.exe convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: auth-service
    spec:
      containers:
        - env:
            - name: ASPNETCORE_Kestrel__Endpoints__Grpc__Protocols
              value: Http2
            - name: ASPNETCORE_Kestrel__Endpoints__Grpc__Url
              value: http://*:50930
            - name: ASPNETCORE_Kestrel__Endpoints__Http1__Protocols
              value: Http1
            - name: ASPNETCORE_Kestrel__Endpoints__Http1__Url
              value: http://*:5093
            - name: ASPNETCORE_URLS
              value: http://*:5093;https://*:50930
            - name: ConsulUrl
              value: http://consul:8500
            - name: InstanceConfig__GrpcPort
              value: "50930"
            - name: InstanceConfig__Http1Port
              value: "5093"
            - name: InstanceConfig__Id
              value: b4f566d1-1234-4a1b-bc3d-c567e8dba7f8
            - name: InstanceConfig__Url
              value: auth-service
          image: sinforge/auth-service
          name: auth-service
          ports:
            - containerPort: 5093
              protocol: TCP
            - containerPort: 50930
              protocol: TCP
      restartPolicy: Always
