apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\vladv\Downloads\kompose-windows-amd64.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: consul
  name: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consul
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\vladv\Downloads\kompose-windows-amd64.exe convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: consul
    spec:
      containers:
        - args:
            - agent
            - -server
            - -ui
            - -node=server-1
            - -bootstrap-expect=1
            - -client=0.0.0.0
          env:
            - name: CONSUL_BIND_INTERFACE
              value: eth0
          image: consul:1.15.4
          name: consul
          ports:
            - containerPort: 8500
              protocol: TCP
      restartPolicy: Always
