apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\vladv\Downloads\kompose-windows-amd64.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: gateway
