apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\vladv\Downloads\kompose-windows-amd64.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: notification-service
  name: notification-service
spec:
  ports:
    - name: "5029"
      port: 5029
      targetPort: 5029
    - name: "50290"
      port: 50290
      targetPort: 50290
  selector:
    io.kompose.service: notification-service
