apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\vladv\Downloads\kompose-windows-amd64.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: notification-service
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: notification-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\vladv\Downloads\kompose-windows-amd64.exe convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: notification-service
    spec:
      containers:
        - env:
            - name: ASPNETCORE_Kestrel__Endpoints__Grpc__Protocols
              value: Http2
            - name: ASPNETCORE_Kestrel__Endpoints__Grpc__Url
              value: http://*:50290
            - name: ASPNETCORE_Kestrel__Endpoints__Http1__Protocols
              value: Http1
            - name: ASPNETCORE_Kestrel__Endpoints__Http1__Url
              value: http://*:5029
            - name: ConsulUrl
              value: http://consul:8500
            - name: InstanceConfig__GrpcPort
              value: "50290"
            - name: InstanceConfig__Http1Port
              value: "5029"
            - name: InstanceConfig__Id
              value: b6f566d1-1234-4a1b-bc3d-c567e8dba7f8
            - name: InstanceConfig__Url
              value: notification-service
          image: sinforge/notification-service
          name: notification-service
          ports:
            - containerPort: 5029
              protocol: TCP
            - containerPort: 50290
              protocol: TCP
      restartPolicy: Always
