apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\vladv\Downloads\kompose-windows-amd64.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: task-service
  name: task-service
spec:
  ports:
    - name: "5234"
      port: 5234
      targetPort: 5234
    - name: "52340"
      port: 52340
      targetPort: 52340
  selector:
    io.kompose.service: task-service
