apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\vladv\Downloads\kompose-windows-amd64.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: task-service
  name: task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: task-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\vladv\Downloads\kompose-windows-amd64.exe convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: task-service
    spec:
      containers:
        - env:
            - name: ASPNETCORE_Kestrel__Endpoints__Grpc__Protocols
              value: Http2
            - name: ASPNETCORE_Kestrel__Endpoints__Grpc__Url
              value: http://*:52340
            - name: ASPNETCORE_Kestrel__Endpoints__Http1__Protocols
              value: Http1
            - name: ASPNETCORE_Kestrel__Endpoints__Http1__Url
              value: http://*:5234
            - name: ASPNETCORE_URLS
              value: http://*:5234;https://*:52340
            - name: ConsulUrl
              value: http://consul:8500
            - name: InstanceConfig__GrpcPort
              value: "52340"
            - name: InstanceConfig__Http1Port
              value: "5234"
            - name: InstanceConfig__Id
              value: b5f566d1-1234-4a1b-bc3d-c567e8dba7f8
            - name: InstanceConfig__Url
              value: task-service
          image: sinforge/task-service
          name: task-service
          ports:
            - containerPort: 5234
              protocol: TCP
            - containerPort: 52340
              protocol: TCP
      restartPolicy: Always
