apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\vladv\Downloads\kompose-windows-amd64.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: task-db
  name: task-db
spec:
  ports:
    - name: "5434"
      port: 5434
      targetPort: 5432
  selector:
    io.kompose.service: task-db
